# shellcheck shell=bash

: "${CAUTIONARY_COLOR_DEFAULT_BG:="#0D1117"}"
: "${CAUTIONARY_COLOR_DEFAULT_FG:="#C9D1D9"}"

: "${CAUTIONARY_COLOR_MUTED_BG:="#161B22"}"
: "${CAUTIONARY_COLOR_MUTED_FG:="#8B949E"}"

: "${CAUTIONARY_COLOR_PRIMARY_BG:="#1F6FEB"}"
: "${CAUTIONARY_COLOR_PRIMARY_FG:="#58A6FF"}"

: "${CAUTIONARY_COLOR_SECONDARY_BG:="#BF4B8A"}"
: "${CAUTIONARY_COLOR_SECONDARY_FG:="#DB61A2"}"

: "${CAUTIONARY_COLOR_SUCCESS_BG:="#238636"}"
: "${CAUTIONARY_COLOR_SUCCESS_FG:="#3FB950"}"

: "${CAUTIONARY_COLOR_RISK_BG:="#9E6A03"}"
: "${CAUTIONARY_COLOR_RISK_FG:="#D29922"}"

: "${CAUTIONARY_COLOR_DANGER_BG:="#DA3633"}"
: "${CAUTIONARY_COLOR_DANGER_FG:="#F85149"}"
